### ISSUE TITLE
Website shows ancient WIP Draft Chapter Policy

### ISSUE THREAD

**Issue by garthoid** [OWASP/www-committee-chapter#24]
When browsing on the OWASP website (owasp.org) and you browse to chapter policies

About->Policies

Then select [Chapters Policy](https://owasp.org/www-policy/operational/chapters)

You will notice on the top right a "next" selection entitled "Chapters Policy - Draft (WIP)"

When selecting this entry you will be sent to a page that is out of date and states:

"Members are invited to provide feedback on this draft policy until January 22, 1970"

This page needs to be removed or at least updated.

**Comment by garthoid** [comment]
I believe the offending page in question is here:

https://github.com/OWASP/www-policy/blob/master/draft-prepublish/chapters.md

**Comment by garthoid** [comment]
I would assign this to myself but I do not appear to have that super-power.

**Comment by garthoid** [comment]
This really should be, or at least linked to, and issue on www-policy (https://github.com/OWASP/www-policy)

**Comment by securestep9** [comment]
Thanks @garthoid - looks like this has been fixed

**Comment by thekyles** [comment]
Closing open issue as Sam verified it as fixed 5 months ago.
